# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='full',
            field=models.TextField(default='Full Article'),
            preserve_default=False,
        ),
    ]
