# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_article_full'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='keyword',
            field=models.TextField(default='key'),
            preserve_default=False,
        ),
    ]
